/* eslint-disable @typescript-eslint/no-explicit-any */
import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { useAppContext } from "../context/AppContext.tsx";
import { api, apiError } from "../lib/api";
import Navbar from "../components/Navbar.tsx"; import Footer from "../components/Footer.tsx"; import AuthModal from "../components/AuthModal.tsx"; import Loader from "../components/Loader.tsx"; import RestaurantHero from "../components/restaurant/RestaurantHero.tsx"; import RestaurantInfo from "../components/restaurant/RestaurantInfo.tsx"; import RestaurantReviews from "../components/restaurant/RestaurantReviews.tsx"; import BookingWidget from "../components/restaurant/BookingWidget.tsx"; import toast from "react-hot-toast";
export default function RestaurantDetail() {
  const { slug } = useParams<{slug:string}>(); const {isAuthenticated,setAuthModalOpen}=useAppContext(); const navigate=useNavigate();
  const [restaurant,setRestaurant]=useState<any>(null); const [loading,setLoading]=useState(true); const [selectedDate,setSelectedDate]=useState(""); const [selectedGuests,setSelectedGuests]=useState("2"); const [selectedSlot,setSelectedSlot]=useState(""); const [slotsAvailability,setSlotsAvailability]=useState<any[]>([]); const [loadingSlots,setLoadingSlots]=useState(false); const [reviews,setReviews]=useState<any[]>([]);
  useEffect(()=>{(async()=>{try{setLoading(true); const {data}=await api.get(`/restaurants/${slug}`); setRestaurant(data.restaurant);}catch(e){toast.error(apiError(e,"Restaurant not found"));}finally{setLoading(false);}})();},[slug]);
  useEffect(()=>{if(!restaurant||!selectedDate)return; (async()=>{try{setLoadingSlots(true); const {data}=await api.get(`/restaurants/${restaurant._id}/availability`,{params:{date:selectedDate,guests:selectedGuests}}); setSlotsAvailability(data.availability||[]);}catch(e){toast.error(apiError(e,"Availability unavailable"));}finally{setLoadingSlots(false);}})();},[restaurant,selectedDate,selectedGuests]);
  useEffect(()=>{if(!restaurant)return; (async()=>{try{const {data}=await api.get(`/restaurants/${restaurant._id}/reviews`);setReviews(data.reviews||[]);}catch{}})();},[restaurant]);
  if(loading)return <Loader text="Loading Restaurant Details..."/>; if(!restaurant)return null;
  const handleReserveClick=()=>{if(!selectedDate)return toast.error("Please select a dining date."); if(!selectedSlot)return toast.error("Please select a dining time slot."); if(!isAuthenticated){setAuthModalOpen(true);return;} navigate(`/booking/${restaurant.slug}?slot=${selectedSlot}&date=${selectedDate}&guests=${selectedGuests}`);};
  return <div className="min-h-screen bg-surface flex flex-col pt-20"><Navbar/><AuthModal/><RestaurantHero restaurant={restaurant}/><main className="grow max-w-7xl w-full mx-auto px-6 md:px-10 py-12"><div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-start"><div className="lg:col-span-8 space-y-12"><RestaurantInfo restaurant={restaurant}/><RestaurantReviews reviews={reviews}/></div><div className="lg:col-span-4 lg:sticky lg:top-36"><BookingWidget restaurant={restaurant} selectedDate={selectedDate} setSelectedDate={setSelectedDate} selectedGuests={selectedGuests} setSelectedGuests={setSelectedGuests} selectedSlot={selectedSlot} setSelectedSlot={setSelectedSlot} slotsAvailability={slotsAvailability} loadingSlots={loadingSlots} isAuthenticated={isAuthenticated} handleReserveClick={handleReserveClick}/></div></div></main><Footer/></div>;
}
